### ISSUE TITLE
"The LINQ expression could not be translated": string[] {}.Contains error if use as LINQ predicate

### ISSUE THREAD

**Issue by mariomenjr** [alexmurari/Exprelsior#13]
Hey there!

I've been giving such a heavy use to this useful and fantastic piece of software that I've been able to spot another issue.

Let me explain the scenario:

### `WHERE x IN ("M", "W")`

As you can see in the image below, the expression `cov('PlanGroup', ['W', 'M'])` has been created to achieve a `WHERE IN`-like predicate.

![image](https://user-images.githubusercontent.com/1946936/95549997-0dcdeb80-09bd-11eb-8602-f6e5c0bf5f56.png)

Once built, I save the returned `Expression` in the `filterExpression` variable, as shown at line 55 in the image below. 

![image](https://user-images.githubusercontent.com/1946936/95550159-466dc500-09bd-11eb-8392-0784a49b2818.png)

That breakpoint doesn't tell us much about what's happening in the expression. That is why in the next image, I am showing the `Debug View` property in the Text Visualizer. It all looks in order.

![image](https://user-images.githubusercontent.com/1946936/95550587-ffcc9a80-09bd-11eb-8531-41d010153e57.png)

However, once is executed in the LINQ `Where` method, an exception is raised:

![image](https://user-images.githubusercontent.com/1946936/95550192-571e3b00-09bd-11eb-8649-8177d7d092fe.png)

Is there something I am missing, like configurations or similar? or is it just something out of the scope of the library? Let me know if more information is needed.

I am using Entity Framework Core and Pomelo to query a MySQL database:

![image](https://user-images.githubusercontent.com/1946936/95551940-9c903780-09c0-11eb-882a-c58fe66a67b8.png)

Just to mention that when an expression is built with the comparison operator `cov` but with an `int[]` type value, everything works fine.

### Trying to debug by myself

As I faced this issue, I tried to debug it myself to contribute to such a useful tool. However, this error message was preventing me from building the solution.

![image](https://user-images.githubusercontent.com/1946936/95551486-bb41fe80-09bf-11eb-8b3a-248f5b935953.png)

**Comment by alexmurari** [comment]
Hi, @mariomenjr!

I think i've found the issue, it's a EF Core limitation, if you look closely, you'll see that Exprelsior builds the `Contains` method call with a `IEqualityComparer` instance of type `StringComparer` with the `OrdinalIgnoreCase` strategy,

Apparently, EF Core doesn't support string comparisons with that `StringComparer`, see issue https://github.com/dotnet/efcore/issues/1222.

One way to solve this is to remove the StringComparer strategy from the Contains method on Exprelsior, but this means that comparisons will not ignore character casing anymore (the default comprarer is `Ordinal`) and I must ponder the implications of that (I even feel it's a breaking change). Or wait for EF Core to support this, which doesn't seen to be happening. 😆 

As for the debuging error, it's because the assemblies are strong-name signed with a password protected key, I will look for a solution for that. In the meantime, you can just modify the project settings to remove the strong-name requirement.
